const assert = require('node:assert/strict');
const { makePage, input } = require('./qa-dom-helper');

const page = makePage('v2-ai-audience.html', {
  extraScripts: ['vendor/bloub/read-yourself-bloub-core.js', 'bloub-audience-runtime.js', 'v2-audience-expression.js', 'v2-audience-stage.js']
});
const { window } = page;
let raf = 0;
window.requestAnimationFrame = () => ++raf;
window.cancelAnimationFrame = () => {};
const tile = window.document.createElement('div');
tile.className = 'audience-tile';
tile.innerHTML = '<div class="avatar">测</div>';
window.document.body.append(tile);
const stage = window.CreatorAudienceStage.mount(tile);
assert.equal(stage.dataset.presentation, 'bloub', 'default stage uses the vendored bloub SVG core');
assert.ok(stage.querySelector('.v2-audience-bloub'), 'bloub core renders an SVG avatar');
const svg = stage.querySelector('.v2-audience-bloub');
assert.match(svg?.outerHTML || '', /<path/);
const mask = svg?.querySelector('mask');
const maskedBody = [...(svg?.querySelectorAll('path') || [])].find(path => path.getAttribute('mask'));
assert(mask, 'bloub SVG must define a luminance mask for eye holes');
assert(maskedBody, 'bloub body must reference the eye-hole mask');
assert.equal(mask.getAttribute('mask-type'), 'luminance');
assert.equal(maskedBody.getAttribute('mask'), `url(#${mask.id})`);
assert.equal(mask.querySelectorAll('path').length, 3, 'mask must contain the body and both eye shapes');
assert.equal(mask.querySelectorAll('path')[1].getAttribute('fill'), 'black', 'eye shapes must cut holes, not paint transparent paths');
assert.equal(svg.querySelector('.v2-audience-bloub-card'), null, 'default stage must not sit on a paper card');
const paintedEyes = [...svg.querySelectorAll('.v2-audience-bloub-eye')];
assert.equal(paintedEyes.length, 2, 'eyes must be painted so they stay visible on the dark stage');
assert.equal(paintedEyes[0].getAttribute('fill'), '#f4efe8');
assert.equal(window.CreatorAudienceStage.applyEvent(tile, { confidence: 'high', scoreDelta: 4, type: 'opening' }), 'interest');
assert.equal(stage.dataset.expression, 'interest');
assert.equal(stage.dataset.bloubState, 'interest');
assert.equal(window.CreatorAudienceExpression.expressionFromEvent({ confidence: 'high', scoreDelta: 4, type: 'opening' }), 'interest', 'bloub cannot alter judgment mapping');
window.CreatorAudienceStage.detachAdapter(stage);
assert.equal(stage.dataset.presentation, 'bloub', 'detaching local Live2D returns to bloub default');

assert.equal(window.document.querySelectorAll('[data-qa-tab]').length, 10);
window.document.querySelector('[data-qa-tab="bloub-audience"]').click();
assert(window.document.querySelector('[data-path="components.bloubAudience.size"]'));
assert(window.document.querySelector('[data-path="components.bloubAudience.ink"]'));
assert(window.document.querySelector('[data-path="components.bloubAudience.holdMs"]'));
assert.equal(window.CreatorQAControls.getState().components.bloubAudience.holdMs, 1600);
input(window, 'components.bloubAudience.size', 72);
input(window, 'components.bloubAudience.x', 12);
input(window, 'components.bloubAudience.holdMs', 900);
input(window, 'components.bloubAudience.card', true);
assert.equal(window.document.documentElement.style.getPropertyValue('--v2-bloub-size'), '72%');
assert.equal(window.document.documentElement.style.getPropertyValue('--v2-bloub-x'), '12px');
assert.equal(window.CreatorQAControls.getState().components.bloubAudience.size, 72);
assert.equal(window.CreatorQAControls.getState().components.bloubAudience.holdMs, 900);
assert.ok(stage.querySelector('.v2-audience-bloub-card'), 'control-panel card toggle restores the paper plate');
const surpris = window.document.querySelector('[data-bloub-preview-state="surpris"]');
assert(surpris, 'control panel must list extra bloub faces for live preview');
surpris.click();
assert.equal(stage.dataset.expression, 'surpris');
assert.equal(stage.querySelector('[data-v2-expression-label]')?.textContent, '惊讶');
window.document.querySelector('[data-bloub-preview-state="drop"]').click();
assert.equal(stage.dataset.expression, 'drop');
assert.equal(window.CreatorAudienceExpression.expressionFromEvent({ confidence: 'high', scoreDelta: 4, type: 'opening' }), 'interest');
page.window.close();
console.log('bloub SVG audience adapter: stage fusion, four-state path, and control-panel wiring passed.');
