const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { makePage, input, read, root, storageKey } = require('./qa-dom-helper');
const plain = value => JSON.parse(JSON.stringify(value));
async function run() {
  const project = { copy: { 'launcher.h1.1': 'Read Yourself', 'launcher.h2.4': '我的镜头练习' }, components: { warpText: { speed: 0.2 } } };
  const dom = makePage('index.html', { project });
  const w = dom.window, d = w.document, mark = d.querySelector('[data-brand-logo]');
  // This DOM suite has no renderer. Exercise the supported no-WebGL fallback
  // while keeping the actual True Focus DOM and its layout listener active.
  w.HTMLCanvasElement.prototype.getContext = () => null;
  w.eval(read('launcher-text-effects.js'));
  const state = () => w.CreatorQAControls.getState();
  const defaults = plain(w.CreatorLogoConfig.defaults);
  const backgroundDefaults = plain(w.CreatorLogoConfig.backgroundDefaults);
  const background = d.querySelector('[data-brand-background]');
  assert.deepEqual(plain(state().components.logo), defaults, 'old configurations acquire Logo defaults');
  assert.deepEqual(plain(state().components.logoBackground), backgroundDefaults, 'legacy project and drafts acquire background defaults without replacing small-logo settings');
  assert.equal(background.style.opacity, '0.08');
  assert.equal(background.getAttribute('aria-hidden'), 'true');
  assert.equal(d.querySelectorAll('[data-qa-logo-group]').length, 2);
  assert(d.querySelector('[data-qa-logo-group="small"]').contains(d.querySelector('[data-path="components.logo.width"]')));
  assert(d.querySelector('[data-qa-logo-group="background"]').contains(d.querySelector('[data-path="components.logoBackground.width"]')));
  assert.equal(mark.nextElementSibling.id, 'launcherTitle');
  assert.equal(d.querySelector('[data-qa-copy-key="launcher.h2.4"]').textContent, '我的镜头练习');
  assert.equal(d.querySelectorAll('[data-qa-tab]').length, 8);
  d.querySelector('.qa-trigger').click();
  for (const name of ['logo', 'components', 'copy', 'text-effects', 'logo']) {
    d.querySelector(`[data-qa-tab="${name}"]`).click();
    assert.equal(d.querySelector('.qa-page:not([hidden])').dataset.qaPage, name);
    assert(!d.querySelector('[data-qa-save-project]').closest('[hidden]'));
  }
  assert.equal(mark.style.color, 'var(--color-text)');
  input(w, 'components.logo.themeColor', 'accent'); input(w, 'theme.accent', '#224466');
  assert.equal(mark.style.color, 'var(--color-brand)');
  assert.equal(d.documentElement.style.getPropertyValue('--color-brand'), '#224466');
  input(w, 'components.logo.followTheme', false);
  assert.equal(state().components.logo.color, '#224466', 'unlinking theme keeps visible color');
  input(w, 'components.logo.color', '#345678'); input(w, 'theme.accent', '#998877');
  assert.equal(state().components.logo.followTheme, false);
  assert.equal(mark.style.color, 'rgb(52, 86, 120)', 'independent color survives theme edits');
  input(w, 'components.logo.followTheme', true);
  assert.equal(mark.style.color, 'var(--color-brand)');
  input(w, 'components.logo.color', '#112233');
  assert.equal(state().components.logo.followTheme, false, 'direct color editing opts out of theme sync');
  for (const [key, value] of [['width',200],['opacity',0.45],['gap',30],['x',16],['y',-12],['align','right']]) input(w, `components.logo.${key}`, value);
  for (const [key, value] of [['width','200px'],['gap','30px'],['x','16px'],['y','-12px']]) assert.equal(mark.style.getPropertyValue(`--logo-${key}`), value);
  assert.equal(mark.style.opacity, '0.45'); assert.equal(mark.dataset.align, 'right');
  input(w, 'components.logo.enabled', false); assert(mark.hidden);
  input(w, 'components.logo.enabled', true); assert(!mark.hidden);
  input(w, 'components.logo.opacity', 0); assert(!mark.hidden, 'zero opacity preserves layout space');
  input(w, 'components.logo.opacity', 0.45);
  const smallBefore = plain(state().components.logo);
  input(w, 'components.logoBackground.themeColor', 'accent');
  assert.equal(background.style.color, 'var(--color-brand)');
  input(w, 'components.logoBackground.followTheme', false);
  assert.equal(state().components.logoBackground.color, '#998877', 'background unlink preserves effective theme color');
  input(w, 'components.logoBackground.color', '#aabbcc'); input(w, 'theme.accent', '#112244');
  assert.equal(background.style.color, 'rgb(170, 187, 204)', 'background independent color survives theme changes');
  input(w, 'components.logoBackground.followTheme', true);
  input(w, 'components.logoBackground.color', '#556677');
  assert.equal(state().components.logoBackground.followTheme, false);
  for (const [key, value] of [['width',150],['opacity',0.12],['x',-25],['y',10]]) input(w, `components.logoBackground.${key}`, value);
  for (const [key, value] of [['width','150%'],['x','-25%'],['y','10%']]) assert.equal(background.style.getPropertyValue(`--background-logo-${key}`), value);
  assert.equal(background.style.opacity, '0.12');
  assert.deepEqual(plain(state().components.logo), smallBefore, 'background controls do not change small Logo');
  input(w, 'components.logo.enabled', false); assert(!background.hidden, 'small visibility does not hide background');
  input(w, 'components.logo.enabled', true);
  input(w, 'components.logoBackground.enabled', false); assert(background.hidden); assert(!mark.hidden);
  input(w, 'components.logoBackground.enabled', true);
  input(w, 'components.logoBackground.opacity', 0); assert(!background.hidden);
  input(w, 'components.logoBackground.opacity', 0.12);
  const expected = plain(state()); let saved;
  w.api = { saveProjectConfig: async value => { saved = value; return { success: true, path: 'test/creator-project-config.js' }; } };
  d.querySelector('[data-qa-save-project]').click(); await new Promise(resolve => setImmediate(resolve));
  const exported = JSON.parse(saved.match(/window\.CreatorProjectConfig\s*=\s*([\s\S]*);\s*$/)[1]).config;
  assert.deepEqual(exported, expected, 'global save includes Logo and all existing settings');
  for (const options of [{ project: exported }, { project, draft: JSON.parse(w.localStorage.getItem(storageKey)) }]) {
    const fresh = makePage('index.html', options);
    assert.deepEqual(plain(fresh.window.CreatorQAControls.getState()), expected);
    assert.equal(fresh.window.document.querySelector('[data-brand-logo]').style.opacity, '0.45');
    assert.equal(fresh.window.document.querySelector('[data-brand-background]').style.opacity, '0.12'); fresh.window.close();
  }
  d.querySelector('[data-qa-logo-reset]').click(); assert.deepEqual(plain(state().components.logo), defaults);
  const after = plain(state()); after.components.logo = expected.components.logo;
  assert.deepEqual(after, expected, 'Logo reset cannot overwrite theme/copy/other components');
  const beforeBackgroundReset = plain(state());
  d.querySelector('[data-qa-background-logo-reset]').click();
  assert.deepEqual(plain(state().components.logoBackground), backgroundDefaults);
  const afterBackgroundReset = plain(state()); afterBackgroundReset.components.logoBackground = beforeBackgroundReset.components.logoBackground;
  assert.deepEqual(afterBackgroundReset, beforeBackgroundReset, 'background reset cannot overwrite small Logo/theme/copy/other components');
  assert.equal(d.querySelectorAll('.true-focus-overlay').length, 1);
  const normalized = w.CreatorLogoConfig.normalize({ width: 9999, opacity: -2, y: Infinity, color: 'url(bad)', align: 'bad' });
  assert.equal(normalized.width, 320); assert.equal(normalized.opacity, 0); assert.equal(normalized.y, 0); assert.equal(normalized.color, defaults.color);
  const backgroundNormalized = w.CreatorLogoConfig.normalizeBackground({ width: 9999, opacity: -1, x: -500, y: Infinity, color: 'url(bad)', align: 'right' });
  assert.deepEqual(plain(backgroundNormalized), { ...backgroundDefaults, width: 200, opacity: 0, x: -100 });
  assert.deepEqual(plain(w.CreatorLogoConfig.normalizeBackground([])), backgroundDefaults);
  assert.equal(d.querySelector('#background-logo-mask image').getAttribute('href'), d.querySelector('#brand-logo-mask image').getAttribute('href'));
  const ids = [...d.querySelectorAll('[id]')].map(node => node.id); assert.equal(new Set(ids).size, ids.length, 'two masks must not introduce duplicate IDs');
  assert(fs.existsSync(path.join(root, d.querySelector('#brand-logo-mask image').getAttribute('href'))));
  assert.match(read('index.html'), /mask-type: alpha/);
  assert.match(read('shared.css'), /\.brand-logo\[hidden\] \{ display: none/);
  assert.match(read('shared.css'), /\.brand-background \{[^}]*grid-area: 1 \/ 1 \/ 2 \/ 2[^}]*overflow: hidden;[^}]*pointer-events: none/);
  assert.equal(dom.qaErrors.length, 0); w.close();
  for (const page of ['v1-camera-baseline.html', 'v2-ai-audience.html', 'v3-creator-studio.html']) {
    const other = makePage(page, { project: exported });
    assert(!other.window.document.querySelector('[data-brand-logo]'), 'training screens remain visually unchanged');
    assert(!other.window.document.querySelector('[data-brand-background]'));
    assert.deepEqual(plain(other.window.CreatorQAControls.getState().components.logo), expected.components.logo);
    assert.deepEqual(plain(other.window.CreatorQAControls.getState().components.logoBackground), expected.components.logoBackground);
    assert(other.window.document.querySelector('[data-qa-tab="logo"]')); assert.equal(other.qaErrors.length, 0); other.window.close();
  }
  const production = makePage('index.html', { project: exported, production: true });
  assert(!production.window.document.querySelector('.qa-panel'));
  assert.equal(production.window.document.querySelector('[data-brand-logo]').style.opacity, '0.45');
  assert.equal(production.window.document.querySelector('[data-brand-background]').style.opacity, '0.12'); production.window.close();
  console.log('Brand Logo: two independent groups, theme/custom colors, eight-tab round trips, bounds, full save/reload, isolated resets, unique masks, legacy copy and training-page isolation passed (DOM; clipping and mask pixels need browser verification).');
}
run().catch(error => { console.error(error); process.exit(1); });
