// Non-visual contract checks only. Founder owns animation/aesthetic acceptance.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM, VirtualConsole } = require('jsdom');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
async function run() {
  const dom = new JSDOM(read('index.html'), { url: 'https://qa.invalid/', runScripts: 'outside-only', pretendToBeVisual: true, virtualConsole: new VirtualConsole() });
  const w = dom.window;
  w.matchMedia = () => ({ matches: false, addEventListener() {}, removeEventListener() {} });
  const key = 'expression-trainer.creator-qa.v1';
  const oldDraft = { theme: { bg: '#faf0f0' }, copy: { 'launcher.h1.1': 'Read Yourself', 'launcher.span.16': 'stale copy must not ship', 'launcher.strong.15': 'stale label' }, fineTune: { launcher: { preserved: true, '[id="trainingLayers"] > a:nth-of-type(1) > h2:nth-of-type(1)': { self: { color: '#ff6600', y: '-25' } } }, 'launcher-fusion': { 'body > main:nth-of-type(1) > section:nth-of-type(1) > div:nth-of-type(1)': { self: { y: '50', 'font-size': '20' } } } }, components: { warpText: { enabled: true, speed: .23 }, logoBackground: { motionMode: 'combined', blinkDuration: 300 }, transcriptCover: { hoverSwapDuration: 720 } } };
  w.localStorage.setItem(key, JSON.stringify(oldDraft));
  for (const file of ['locales/zh-CN.js', 'locales/en-US.js', 'i18n.js', 'creator-project-config.js', 'home-fusion.js', 'brand-logo.js', 'product-shell.js', 'vertical-marquee-config.js', 'qa-element-editor.js', 'config-file-store.js', 'control-panel.js', 'vendor/magic-ui/marquee.js', 'launcher-transcript.js', 'launcher-text-effects.js']) w.eval(read(file));
  await new Promise(resolve => setTimeout(resolve, 30));
  const state = w.CreatorQAControls.getState();
  assert.equal(state.theme.bg, '#faf0f0');
  assert.equal(state.components.warpText.enabled, false);
  assert.equal(state.components.warpText.speed, .23);
  assert.equal(state.components.trueFocus.layout, 'stacked');
  assert.equal(state.components.logoBackground.motionMode, 'combined');
  assert.equal(state.components.logoBackground.blinkDuration, 300);
  assert.equal(state.fineTune.launcher.preserved, true);
  assert.equal(state.fineTune.launcher['[id="trainingLayers"] > a:nth-of-type(1) > h2:nth-of-type(1)'].self.y, undefined, 'old homepage box offsets must not fight the current layout');
  assert.equal(state.fineTune.launcher['[id="trainingLayers"] > a:nth-of-type(1) > h2:nth-of-type(1)'].self.color, '#ff6600');
  assert.equal(state.fineTune['launcher-fusion']['body > main:nth-of-type(1) > section:nth-of-type(1) > div:nth-of-type(1)'].self.y, undefined);
  assert.equal(state.fineTune['launcher-fusion']['body > main:nth-of-type(1) > section:nth-of-type(1) > div:nth-of-type(1)'].self['font-size'], '20');
  assert.equal(state.copy['launcher.h1.1'], 'Read Yourself', 'September 6 homepage copy stays');
  assert.equal(state.copy['launcher.span.16'], undefined, 'homepage saves must discard copy keys with no real element');
  assert.equal(state.copy['launcher.strong.15'], undefined, 'stale homepage labels must not become UI requirements');
  assert.equal(w.localStorage.getItem(`${key}.before-home-fusion`), JSON.stringify(oldDraft));
  assert(w.document.querySelector('.product-wordmark [data-brand-logo]'));
  assert(w.document.querySelector('.magic-marquee-group'));
  assert(!w.document.querySelector('.sentence-tools'));
  assert.equal(w.document.querySelector('.true-focus-overlay').dataset.focusLayout, 'stacked');
  const active = () => w.document.querySelector('.magic-marquee-group .transcript-pair');
  const viewport = w.document.querySelector('[data-transcript-stream]');
  assert.equal(state.components.transcriptCover.swapTrigger, 'blink');
  assert.equal(state.components.transcriptCover.height, 480);
  assert.equal(state.components.logoBackground.opacity, .12);
  assert.equal(state.components.logoBackground.width, 100);
  assert.equal(state.components.logoBackground.x, 0);
  active().dispatchEvent(new w.MouseEvent('pointerover', { bubbles: true }));
  assert.equal(active().getAttribute('aria-pressed'), 'false', 'hover must not trigger a rewrite in blink mode');
  w.document.dispatchEvent(new w.CustomEvent('creator:logo-blink'));
  assert.equal(active().getAttribute('aria-pressed'), 'true', 'one blink reveals optimized sentences');
  w.document.dispatchEvent(new w.CustomEvent('creator:logo-blink'));
  assert.equal(active().getAttribute('aria-pressed'), 'false', 'the next blink restores the original');
  assert.equal(w.document.querySelector('[data-home-motion-toggle]'), null, 'homepage does not expose a pause control');
  w.CreatorQAControls.updateMarquee({ displayMode: 'single' });
  const animation = { currentTime: 0 };
  viewport.querySelector('.magic-marquee-group').getAnimations = () => [animation];
  w.document.querySelector('[data-marquee-step="1"]').click();
  assert(animation.currentTime > 0, 'panel seeks the continuous animation');
  const input = (name, value) => {
    const node = w.document.querySelector(`[data-path="${name}"]`);
    if (node.type === 'checkbox') node.checked = value; else node.value = value;
    node.dispatchEvent(new w.Event('input', { bubbles: true }));
  };
  input('components.transcriptCover.displayMode', 'stream');
  assert(w.document.querySelector('.magic-marquee-group'));
  input('components.transcriptCover.displayMode', 'single');
  assert(w.document.querySelector('.magic-marquee-group'));
  assert.equal(w.document.querySelector('[data-transcript-cover]').dataset.displayMode, 'single');
  input('components.trueFocus.layout', 'inline');
  assert.equal(w.document.querySelector('.true-focus-overlay').dataset.focusLayout, 'inline');
  w.CreatorI18n.setLocale('en-US');
  assert.equal(w.document.querySelector('.fusion-start').textContent, 'Start with V1');
  assert.match(active().textContent, /Before you film/);
  w.CreatorI18n.setLocale('zh-CN');
  assert.match(w.document.querySelector('.launcher-lead').textContent, /When your ideas become content/);
  assert(!w.document.querySelector('[data-path="components.transcriptCover.cycleMs"]'));
  input('components.transcriptCover.scrollDuration', 26000);
  assert.equal(viewport.style.getPropertyValue('--duration'), '26000ms');
  input('components.transcriptCover.scrollDuration', 60000);
  assert.equal(viewport.style.getPropertyValue('--duration'), '60000ms');
  assert.match(read('vendor/magic-ui/marquee.css'), /linear infinite/);
  assert(!read('launcher-transcript.js').includes('settings.cycleMs'));
  input('components.transcriptCover.playbackMode', 'static');
  assert.equal(viewport.dataset.playbackMode, 'static');
  assert.equal(viewport.dataset.paused, 'true');
  const saved = JSON.parse(w.localStorage.getItem(key));
  assert.equal(saved.components.homeFusion.version, 1);
  assert.equal(w.CreatorHomeFusion.migrate(saved).components.transcriptCover.playbackMode, 'static');
  dom.window.close();
  console.log('PASS home fusion: migration, controls, locale, continuous engine, speed binding and manual mode (not visual QA)');
}
run().catch(error => { console.error(error); process.exit(1); });
