const assert = require('node:assert/strict');
const { makePage, read } = require('./qa-dom-helper');
const dom = makePage('v2-ai-audience.html', { extraScripts: ['v2-focus.js', 'expression-analysis.js', 'v2-session-model.js', 'v2-rule-judge.js', 'v2-review.js', 'v2-interest-panel.js'] });
const w = dom.window, d = w.document;
const prefix = 'body > main:nth-of-type(1) > section:nth-of-type(1) > div:nth-of-type(2)';
const config = { fineTune: { v1: { keep: true }, v2: { [prefix + ' > div:nth-of-type(1)']: { self: { width: '600' } }, [prefix + ' > div:nth-of-type(2)']: { self: { width: '440', x: '-210', opacity: '.8' } } } } };
w.CreatorV2Focus.migrate(config);
assert(Math.abs(config.components.v2Stage.audienceShare - 57.6923) < .001);
assert(config.fineTune.v1.keep);
assert.equal(config.fineTune.v2['[id="v2CreatorStage"]'].self.opacity, '.8');
assert.equal(config.fineTune.v2['[id="v2CreatorStage"]'].self.x, undefined);
assert.equal(config.components.v2Focus.visualVersion, 3);
const once = JSON.stringify(config); w.CreatorV2Focus.migrate(config); assert.equal(JSON.stringify(config), once);
const oldSidebar = { fineTune: { v1: { untouched: true }, v2: { 'button[data-pressure="medium"]': { self: { 'background-color': '#8389d2', 'font-size': '15px' } } } } };
w.CreatorV2Focus.migrate(oldSidebar);
assert.equal(oldSidebar.fineTune.v2['button[data-pressure="medium"]'].self['background-color'], undefined);
assert.equal(oldSidebar.fineTune.v2['button[data-pressure="medium"]'].self['font-size'], '15px');
assert(oldSidebar.fineTune.v1.untouched);
oldSidebar.fineTune.v2['button[data-pressure="medium"]'].self['background-color'] = '#fafafa';
w.CreatorV2Focus.migrate(oldSidebar);
assert.equal(oldSidebar.fineTune.v2['button[data-pressure="medium"]'].self['background-color'], '#fafafa', 'new founder tuning is preserved after the one-time migration');
assert.equal(d.querySelector('.side-panel.left .metric-list'), null);
assert.equal(d.querySelector('.side-panel.left .goal-card'), null);
assert(d.querySelector('.audience-primary-stage [data-v2-interest-panel]'));
assert(d.querySelector('.v2-transcript-desk').contains(d.getElementById('liveTranscript')), 'transcript has its own desk');
assert(!d.querySelector('.audience-primary-room').contains(d.getElementById('liveTranscript')), 'transcript never overlays the stage');
assert.equal(d.querySelector('.v2-feedback-toggle').parentElement, d.querySelector('.side-panel.right'), 'collapse handle belongs to the panel edge');
assert.match(read('v2-focus.css'), /v2-feedback-toggle svg \{[^}]*scaleX\(-1\)/, 'expanded handle points toward the closed edge');
assert.match(read('shared.css'), /\.qa-panel \{[^}]*z-index: 421/, 'QA panel stays above the audience selector');
const button = d.querySelector('.v2-feedback-toggle'); button.click();
assert.equal(button.getAttribute('aria-expanded'), 'false'); assert(d.getElementById('v2FeedbackBody').hidden);
assert.equal(button.getAttribute('aria-label'), '展开实时反馈');
button.click(); assert.equal(button.getAttribute('aria-expanded'), 'true');
assert.equal(d.querySelector('[data-v2-lines]').children.length, 0, 'no fabricated curve before speech');
const round = { status: 'complete', hasScore: true, score: 50, points: [{ kind: 'value', t: 0, score: 100 }, { kind: 'value', t: 15000, score: 50 }], events: [], segments: [{ status: 'final', text: '其实就是有很多东西。其实就是有很多东西。' }] };
d.dispatchEvent(new w.CustomEvent('creator:v2-session-change', { detail: { active: round } }));
assert.equal(d.querySelector('.v2-interest-line').getAttribute('d'), 'M26.0 8.0 L191.0 41.0');
assert(d.querySelector('[data-v2-lines] path[fill="url(#v2InterestFill)"]'), 'valid data receives a readable area signal');
assert.equal(d.querySelector('[data-v2-interest-panel] .v2-chart-data'), null, 'data details do not cover the stage');
assert(d.querySelector('[data-v2-chart-context] .v2-chart-data'));
assert.match(d.querySelector('[data-v2-time-axis]').textContent, /00:15/);
assert.equal(d.querySelector('[data-v2-table]').rows.length, 2);
assert(!d.querySelector('[data-v2-report]').hidden);
assert(!d.querySelector('[data-v2-report]').open, 'report is available on demand');
assert.match(d.querySelector('[data-v2-word-review]').textContent, /填充词.*模糊词/s);
round.status = 'running';
d.dispatchEvent(new w.CustomEvent('creator:v2-session-change', { detail: { active: round } }));
assert(d.querySelector('[data-v2-report]').hidden, 'a new round hides previous diagnostics');
w.close();
console.log('V2 focus: proportional migration, collapse, chart axes, empty data and end-of-round diagnostics passed.');
